version: "3"
services:
 web:
  build:
   context: ./web
   dockerfile: Dockerfile
  env_file:
   - .env
  ports:
   - ${WEB_PORT}:4200
  volumes:
   - ./web:/app
  depends_on:
   - api
 api:
  build:
   context: ./api
   dockerfile: Dockerfile
  env_file:
   - .env
  ports:
   - ${API_PORT}:${API_PORT}
  volumes:
   - ./api:/app
  depends_on:
   - db
 db:
  image: postgres:15-alpine
  environment:
   - POSTGRES_USER=${DB_USERNAME}
   - POSTGRES_PASSWORD=${DB_PASSWORD}
   - POSTGRES_DB=${DB_DATABASE}
  ports:
   - ${DB_PORT}:5432
  volumes:
   - ./db:/var/lib/postgresql/data
